spring.application.name=KrishiEaze

spring.datasource.url=jdbc:postgresql://localhost:5432/krishieaze
spring.datasource.username=postgres
spring.datasource.password=2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

logging.level.org.springframework.security=debug
server.port=8080
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
security.jwt.secretKey=${JWT_SECRET:fawihfjbfjaewbfurwy274fiaewhfawd4ffnsnfkasni34984uwrjfeur84y5984y54h5fgkejgrneskngeskgi4wiio4wjklmq8934u54igmv,dsnkvheigewngenvkenfkjgh4ihtihytirhegewrngk4wh89g5hknfhsnmvdlkjw4iph}
security.jwt.issuer=${JWT_ISSUER:api.substring.com}
security.jwt.access-ttl-seconds=${JWT_ACCESS_TTL_SECOND:300}
security.jwt.refresh-ttl-seconds=${JWT_REFRESH_TTL_SECOND:86400}
security.jwt.refresh-token-cookie-name=${JWT_REFRESH_COOKIE_NAME:refreshToken}
security.jwt.cookie-secure=${JWT_COOKIE_SECURE:true}
security.jwt.cookie-http-only=${JWT_COOKIE_HTTP_ONLY:true}
security.jwt.cookie-same-site=${JWT_COOKIE_SAME_SITE:lax}
# Leave blank for localhost development
security.jwt.cookie-domain=${JWT_COOKIE_DOMAIN:}
server.error.include-message=always
server.error.include-binding-errors=always

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
