export const ViewState = {
    LANDING: 'LANDING',
    DASHBOARD: 'DASHBOARD',
    MANDI_PRICES: 'MANDI_PRICES',
    SELL_PRODUCE: 'SELL_PRODUCE',
    ORDER_DETAILS: 'ORDER_DETAILS',
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP'
};
